databases:
  - name: bookingdoctor
    databaseName: bookingapidb_4djm
    user: sattar

services:
  - type: web
    name: booking.doctor.api.v1
    runtime: ruby
    buildCommand: "bundle install rails db:create rails db:migrate"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bookingapidb_4djm
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
